name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chaichontat/pages_test:main
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          r -e "rmarkdown::render(\"index.Rmd\", output_dir = \"./public\", output_format = \"all\")"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: HTML
          path: public/index.html
          retention-days: 7

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: r-lib/actions/setup-r@v1
    #   - uses: r-lib/actions/setup-pandoc@v1
    #   - uses: r-lib/actions/setup-tinytex@v1

    #   - name: Restore R package cache
    #     uses: actions/cache@v2
    #     with:
    #       path: ${{ env.R_LIBS_USER }}
    #       key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
    #       restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

    #   - name: Query dependencies
    #     run: |
    #       options(Ncpus = 2)
    #       install.packages('devtools')
    #       devtools::install_github('rstudio/distill@33f858a0e56cd083d55d8ff8df2ed7eecd27372a')
    #     shell: Rscript {0}

    #   - name: Render
    #     run: |
    #       rmarkdown::render("index.Rmd", output_dir = "./public")
    #     shell: Rscript {0}
    #     env:
    #       LANG: en_US.UTF-8
