name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chaichontat/pages_test:main
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          r -e "rmarkdown::render(\"index.Rmd\", output_dir = \"./public\", output_format = \"all\")"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: public/index.html
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  firebase:
    needs: deploy
    runs-on: ubuntu-latest
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: index.html

      - name: Deploy to Firebase for PR
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_PAGES_C50B1 }}"
          projectId: github-pages-c50b1
